services:
  caddy:
    image: caddy:2-alpine
    restart: always
    networks:
      - traefik-network
    volumes:
      - application-data:/app:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.quemindicar.rule=Host(`quemindicar.com.br`) || Host(`www.quemindicar.com.br`)
      - traefik.http.routers.quemindicar.tls=true
      - traefik.http.routers.quemindicar.tls.certResolver=lets-encrypt
      - traefik.http.services.quemindicar.loadBalancer.server.port=80

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      - local-network
      - traefik-network
    env_file:
      - .env
    depends_on:
      - database    
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm start -- --hostname 0.0.0.0"
    volumes:
      - application-data:/app/public

  studio:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      - local-network
      - traefik-network
    env_file:
      - .env
    depends_on:
      - app
    command: sh -c "npx prisma studio --hostname 0.0.0.0"
    labels:
      - traefik.enable=true
      - traefik.http.routers.quemindicar-prisma-studio.rule=Host(`studio.quemindicar.com.br`)
      - traefik.http.routers.quemindicar-prisma-studio.tls=true
      - traefik.http.routers.quemindicar-prisma-studio.tls.certResolver=lets-encrypt
      - traefik.http.routers.quemindicar-prisma-studio.middlewares=basic-auth@file
      - traefik.http.services.quemindicar-prisma-studio.loadBalancer.server.port=5555

  database:
    image: postgres:17-alpine
    restart: always
    networks:
      - local-network
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  application-data:

networks:
  local-network:
  traefik-network:
    external: true
