version: "3.8"

services:
  app:
    # Use 'build' if you have a Dockerfile in the same directory.
    # Otherwise, you can use 'image' if you have a pre-built image.
    build: .
    container_name: quemindicar-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Use the environment variables from your .env file
      - DATABASE_URL=postgresql://ssit_owner:ssit_2089_Inf0@db:5432/quemindicar_db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - STRIPE_MONTHLY_PRICE_ID=${STRIPE_MONTHLY_PRICE_ID}
      - STRIPE_SEMESTRAL_PRICE_ID=${STRIPE_SEMESTRAL_PRICE_ID}
      - STRIPE_ANUAL_PRICE_ID=${STRIPE_ANUAL_PRICE_ID}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL=${NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL}
    depends_on:
      - db
    # In a production environment, you might want to use a volume for persistent storage
    volumes:
      - ./quemindicar:/app

  # Database service
  db:
    image: postgres:17
    container_name: quemindicar-db
    restart: always
    environment:
      POSTGRES_USER: ssit_owner
      POSTGRES_PASSWORD: ssit_2089_Inf0
      POSTGRES_DB: quemindicar_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
